### ISSUE TITLE
Unable to contribute PR as there are no existing commits

### ISSUE THREAD

**Issue by ronaldtse** [googlefonts/carlito#1]
As per https://github.com/google/fonts/issues/1441#issuecomment-754068542 I've tried to fork the repo to make a PR but GitHub does not allow forking (hence PRs) on repositories without commits.

I've uploaded it to our temporary repository here: https://github.com/fontist/carlito

Will rebase onto the repository once it can be forked. Thanks!

cc: @davelab6

**Comment by ronaldtse** [comment]
Ping @davelab6 for attention. Thanks 😉

**Comment by mfwitten** [comment]
Please address this issue.  
It's time to finish this.

**Comment by davelab6** [comment]
Fixed

**Comment by ronaldtse** [comment]
Thanks @davelab6 ! I've submitted the pull request at #2 .
